org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Basic Information
fileName=FastWorkbench
modName=Fast Workbench
modGroup=dev.shadowsoffire
modid=fastbench
author=Shadows_of_Fire
desc=Speeding up crafting operations - massively.
version=9.1.2

# Dependencies
mcVersion=1.21.1
javaVersion=21
forgeVersion=21.1.187
parchmentVersion=2024.11.17-1.21.1
jeiVersion=19.21.2.313
jadeVersion=15.10.2
#curiosVersion=9.5.1+1.21.1
placeboVersion=9.9.0

# Mixins
mixin=true
mixinVersion=0.8.7

# Publishing
requiredDeps=placebo
#optionalDeps=
#incompatibleDeps=
releaseType=release
modLoaders=NeoForge
curseforgeProjectId=288885

# Tests
enableTests=false
