org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Basic Information
fileName=FastWorkbench
modName=Fast Workbench
modGroup=dev.shadowsoffire
modid=fastbench
author=Shadows_of_Fire
desc=Speeding up crafting operations - massively.
version=10.0.0-beta1

# Dependencies
mcVersion=26.1.2
javaVersion=25
forgeVersion=26.1.2.22-beta
jeiVersion=29.5.0.26
jadeVersion=26.0.9
#curiosVersion=9.5.1+1.21.1
placeboVersion=10.0.0-beta5

# Mixins
mixin=true
mixinVersion=0.8.7

# Publishing
requiredDeps=placebo
#optionalDeps=
#incompatibleDeps=
releaseType=release
modLoaders=NeoForge
curseforgeProjectId=288885

# Tests
enableTests=false
