org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Basic Information
fileName=FastWorkbench
modName=Fast Workbench
modGroup=dev.shadowsoffire
modid=fastbench
author=Shadows_of_Fire
desc=Speeding up crafting operations - massively.
version=9.1.1

# Dependencies
mcVersion=1.21
javaVersion=21
forgeVersion=21.0.65-beta
parchmentVersion=2024.06.23-1.21
jeiVersion=19.0.0.11
jadeFileId=5444008
#curiosVersion=7.3.4+1.20.4
placeboVersion=9.3.3
#topVersion=1.20.0-9.0.0-1
#patchouliVersion=1.19.2-76

# Mixins
mixin=true
mixinVersion=0.8.5

# Publishing
requiredDeps=placebo
#optionalDeps=
#incompatibleDeps=
releaseType=beta
modLoaders=NeoForge
curseforgeProjectId=288885
#modrinthProjectId=